### ISSUE TITLE
Tinkerkit touch example throwing errors

### ISSUE THREAD

**Issue by ShielderJohn** [rwaldron/johnny-five#1142]
**Board**: Arduino UNO
**Shield**: Tinkerkit
**Hardware having issue with**: touch sensor
**Johhny-five version**: 0.9.51

When trying to run the example provided for **Tinkerkit Touch** sensor:

```javascript
var five = require("johnny-five");

new five.Board().on("ready", function() {
  // Attaching to an O* pin in a deviation from
  // TinkerKit tutorials which instruct to attach
  // the touch to an I* pin.
  //
  // For the "touch" module, simply use a Button
  // instance, like this:
  var touch = new five.Button("O5");

  ["down", "up", "hold"].forEach(function(type) {
    touch.on(type, function() {
      console.log(type);
    });
  });
});
```

The following error is thrown:

```
/Users/Juan/Downloads/johnny-five-master/node_modules/firmata/lib/firmata.js:849
  this.pins[pin].mode = mode;
                      ^

TypeError: Cannot set property 'mode' of undefined
    at Board.pinMode (/Users/Juan/Downloads/johnny-five-master/node_modules/firmata/lib/firmata.js:849:23)
    at Button.Controllers.DEFAULT.initialize.value (/Users/Juan/Downloads/johnny-five-master/lib/button.js:31:17)
    at new Button (/Users/Juan/Downloads/johnny-five-master/lib/button.js:257:10)
    at Board.<anonymous> (/Users/Juan/Downloads/johnny-five-master/eg/tinkerkit-touch.js:10:15)
    at emitNone (events.js:72:20)
    at Board.emit (events.js:166:7)
    at doNTCallback0 (node.js:417:9)
    at process._tickDomainCallback (node.js:387:13)
```

**Comment by rwaldron** [comment]
Thanks for the report! 

I'll have a look at this today
