### ISSUE TITLE
HCSR04 - Intel Edison pingRead error

### ISSUE THREAD

**Issue by m0rg0t** [rwaldron/johnny-five#1167]
Trying to use HCSR04 proximity ultrasonic sensor with connection to analog pin

```
  var proximity = new five.Proximity({
    controller: "HCSR04",
    pin: "A2"
  });

  proximity.on("data", function() {
    console.log("Proximity: ");
    console.log("  cm  : ", this.cm);
    console.log("  in  : ", this.in);
    console.log("-----------------");
  });

  proximity.on("change", function() {
    console.log("The obstruction has moved.");
  });
```

get error

`TypeError: Object #<Galileo> has no method 'pingRead'`

Full:

```
ERROR: TypeError: Object #<Galileo> has no method 'pingRead'
    at Proximity.<anonymous> (/home/root/node_modules/johnny-five/lib/proximity.js:196:19)
    at Proximity.Controllers.HCSR04.initialize.value (/home/root/node_modules/johnny-five/lib/proximity.js:202:9)
    at new Proximity (/home/root/node_modules/johnny-five/lib/proximity.js:466:10)
    at Board.connectedUsersArray (/home/root/.node_app_slot/main.js:108:19)
    at Board.emit (events.js:117:20)
    at process._tickCallback (node.js:448:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:935:3
```

**Comment by wicktus** [comment]
Hello,

http://johnny-five.io/platform-support/#intel-edison-arduino

The Edison board is **NOT** compatible with ping ;), have you tried using the Proximity ?

**Comment by lyzadanger** [comment]
Hi! The `galileo-io` IO plugin (used by both Galileos and Edisons with Johnny-Five) doesn't have support for `Ping` (there's likely a constraint or hardware reason for that). I'm going to go ahead and close this issue. Let me know if I can help further!

**Comment by rwaldron** [comment]
To make this work, you _can_ use the available I2C backpack configuration, as shown here: http://johnny-five.io/examples/proximity-hcsr04-i2c/ Simply replace the Arduino UNO with the Edison (and connect wires accordingly)
