### ISSUE TITLE
A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by facetime88** [rwaldron/johnny-five#1351]
Hi Johnny,

I tried to follow the installation (include with the prerequisites install under windows), but I am stuck with this error when running my app:

> Uncaught Error: A dynamic link library (DLL) initialization routine failed.
\\?\E:\client\node_modules\johnny-five\node_modules\serialport\build\Release\serialport.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (E:\client\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (E:\client\node_modules\johnny-five\node_modules\serialport\lib\bindings.js:3:35)

I am on windows 10 x64, trying to connect to arduino mega.
Thank you.

**Comment by facetime88** [comment]
Okay seems this is a serialport issue. Try to follow the guide here: 

> https://github.com/EmergingTechnologyAdvisors/node-serialport#electron

And still didn't work. Then uninstall and install again. This time it's working. So I do not know why.
