### ISSUE TITLE
 Error installing pingFirmata

### ISSUE THREAD

**Issue by luisantoir** [rwaldron/johnny-five#1517]
Hi, I'm new to the Arduino world.
I'm trying to install pingFinamta to use the HC-SR04 sensor but I do not do it.
These are the steps of the installation and the error
<pre><code>
PS D:\node_arduino\radar> npm install nodebots-interchange -g
C:\Users\skums\AppData\Roaming\npm\interchange -> C:\Users\skums\AppData\Roaming\npm\node_modules\nodebots-interchange\bin\cli.js
+ nodebots-interchange@1.3.0
updated 1 package in 26.39s
PS D:\node_arduino\radar> interchange install hc-sr04 -a uno -p COM4 --firmata
Installing hc-sr04 from npm
npm WARN radar@1.0.0 No description
npm WARN radar@1.0.0 No repository field.

+ nodebots-hcsr04@0.5.0
updated 1 package in 7.255s
ReferenceError: manifest is not defined
    at Interchange.download_from_npm (C:\Users\skums\AppData\Roaming\npm\node_modules\nodebots-interchange\lib\interchange.js:252:48)
    at Interchange.check_firmware (C:\Users\skums\AppData\Roaming\npm\node_modules\nodebots-interchange\lib\interchange.js:440:10)
    at Interchange.install_firmware (C:\Users\skums\AppData\Roaming\npm\node_modules\nodebots-interchange\lib\interchange.js:134:10)
    at Command.<anonymous> (C:\Users\skums\AppData\Roaming\npm\node_modules\nodebots-interchange\bin\cli.js:41:19)
    at Command.listener (C:\Users\skums\AppData\Roaming\npm\node_modules\nodebots-interchange\node_modules\commander\index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (C:\Users\skums\AppData\Roaming\npm\node_modules\nodebots-interchange\node_modules\commander\index.js:654:12)
    at Command.parse (C:\Users\skums\AppData\Roaming\npm\node_modules\nodebots-interchange\node_modules\commander\index.js:474:21)
    at Object.<anonymous> (C:\Users\skums\AppData\Roaming\npm\node_modules\nodebots-interchange\bin\cli.js:45:9)
</code></pre>

version node v8.9.3
version johnny-five  1.0.0
version nodebots-interchange 1.3.0
windows 10

**Comment by dtex** [comment]
Hi @luisantoir 

This is a problem in nodebots-interchange so I have opened an issue for you over there.

https://github.com/johnny-five-io/nodebots-interchange/issues/36
