### ISSUE TITLE
Beaglebone crashes sometimes when deploying

### ISSUE THREAD

**Issue by melody8801** [rwaldron/johnny-five#1539]
That error happens, if the config of a node is wrong. So that is not a Problem. Bud: sometimes it crashes also, even though everything before worded well and nothing was changed in the J5 nodes.

Thanks for your good work. 

```
Dec  6 22:53:07 beaglebone Node-RED[1272]: 1544136787407 Available BeagleBone-IO
Dec  6 22:53:07 beaglebone Node-RED[1272]: 6 Dec 22:53:07 - [info] Started flows
Dec  6 22:53:07 beaglebone Node-RED[1272]: 6 Dec 22:53:07 - [red] Uncaught Exception:
Dec  6 22:53:07 beaglebone Node-RED[1272]: 6 Dec 22:53:07 - TypeError: Cannot read property 'port' of null
Dec  6 22:53:07 beaglebone Node-RED[1272]:     at Board.finalizeAndBroadcast (/usr/local/lib/node_modules/node-red-contrib-gpio/node_modules/johnny-five/lib/board.js:370:19)
Dec  6 22:53:07 beaglebone Node-RED[1272]:     at Board.<anonymous> (/usr/local/lib/node_modules/node-red-contrib-gpio/node_modules/johnny-five/lib/board.js:313:32)
Dec  6 22:53:07 beaglebone Node-RED[1272]:     at BeagleBone.g (events.js:292:16)
Dec  6 22:53:07 beaglebone Node-RED[1272]:     at emitNone (events.js:91:20)
Dec  6 22:53:07 beaglebone Node-RED[1272]:     at BeagleBone.emit (events.js:185:7)
Dec  6 22:53:07 beaglebone Node-RED[1272]:     at BeagleBone.<anonymous> (/usr/local/lib/node_modules/beaglebone-io/lib/beaglebone.js:27:10)
Dec  6 22:53:07 beaglebone Node-RED[1272]:     at runCallback (timers.js:672:20)
Dec  6 22:53:07 beaglebone Node-RED[1272]:     at tryOnImmediate (timers.js:645:5)
Dec  6 22:53:07 beaglebone Node-RED[1272]:     at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by dtex** [comment]
Sorry nobody here has responded. I bet you might have better luck over at https://github.com/julianduque/beaglebone-io That's where the Johnny-Five on BeagleBone experts are.
