### ISSUE TITLE
SyntaxError on Node 4.8.2

### ISSUE THREAD

**Issue by jpink** [rwaldron/johnny-five#1545]
I get SyntaxError when running at following setup:
- Debian Stretch 32-bit (i686)
- Node.js 4.8.2 from Debian official repo (can't get any NodeSource version working)
- Arduino Uno with FirmataStandard installed.
- Simple "Hello World!" blinking LED test.
Output is following:
```
Linux pc 4.9.0-8-686-pae #1 SMP Debian 4.9.130-2 (2018-10-27) i686
...
root@pc:~# js -v
v4.8.2
root@pc:~# js index.js
/root/node_modules/johnny-five/lib/repl.js:98
        for (let i = 0; i < state.board.length; i++) {
             ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/node_modules/johnny-five/lib/board.js:14:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

When i test it on Windows & Node 10.x it is working fine. I need this on linux, can't get updated Node working and the tutorial prefers Node.js 4.2.1 LTS anyway.

**Comment by dtex** [comment]
For Node.js version 4.0, the last functioning release was serialport@6 You could downgrade to that and try it out, but I fear you will run into other problems. 

I believe that for long-term node on Debian happiness you should fight this battle from the other end and get an LTS version of node working for you. Johnny-Five is only (officially) tested against LTS releases (6, 8, 10).
