### ISSUE TITLE
(node:943) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by maka-io** [rwaldron/johnny-five#1568]
Can't seem to get this working.

Using Raspberry Pi v2, arm32v7, inside a docker container (arm arch).

Any suggestions?

```
[192.168.1.76](node:943) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'filter' of undefined
[192.168.1.76]    at Board.<anonymous> (/bundle/bundle/programs/server/npm/node_modules/johnny-five/lib/board.js:53:26)
[192.168.1.76]    at promise.then.err (/bundle/bundle/programs/server/npm/node_modules/johnny-five/node_modules/serialport/lib/serialport.js:629:14)
```

**Comment by dtex** [comment]
Sorry nobody has responded before now. I think it's because this question is better suited for the https://github.com/serialport/node-serialport repo.

I did a quick search over there and noticed this issue which may have the same cause: https://github.com/serialport/node-serialport/issues/1090

Since this is a serialport issue I'm going to close it here.
