### ISSUE TITLE
arduino uno work properly with arduino ide but not with johnny-five

### ISSUE THREAD

**Issue by moeinrahimi** [rwaldron/johnny-five#1670]
I can turn on led using arduino ide itself but not with johnny-five . 
```
var five = require("johnny-five");
var board = new five.Board({port:'COM3'});

board.on("ready", function () {
  console.log('ready')
  var led = new five.Led(13);
  led.blink(500);

});
```
output
```
 node index.js
1585150143918 Connected COM3  
1585150153922 Device or Firmware Error A timeout occurred while connecting to the Board. 

Please check that you've properly flashed the board with the correct firmware.
See: https://github.com/rwaldron/johnny-five/wiki/Getting-Started#trouble-shooting

If connecting to a Leonardo or Leonardo clone, press the 'Reset' button on the board, wait approximately 11 seconds for complete reset, then run your program again. 
events.js:312
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
  type: 'error',
  timestamp: 1585150153922,
  class: 'Device or Firmware Error',
  message: 'A timeout occurred while connecting to the Board. \n' +
    '\n' +
    "Please check that you've properly flashed the board with the correct firmware.\n" +
    'See: https://github.com/rwaldron/johnny-five/wiki/Getting-Started#trouble-shooting\n' +
    '\n' +
    "If connecting to a Leonardo or Leonardo clone, press the 'Reset' button on the board, wait approximately 11 seconds for complete reset, then run your program again.",
  data: null
})
    at Board.emit (events.js:310:17)
    at Board.EventEmitter.emit (domain.js:482:12)
    at Board.log (E:\projects\arduino\sample\node_modules\johnny-five\lib\board.js:645:8)
    at Board.<computed> [as error] (E:\projects\arduino\sample\node_modules\johnny-five\lib\board.js:656:14)
    at Board.<anonymous> (E:\projects\arduino\sample\node_modules\johnny-five\lib\board.js:387:14)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'ERR_UNHANDLED_ERROR',
  context: {
    type: 'error',
    timestamp: 1585150153922,
    class: 'Device or Firmware Error',
    message: 'A timeout occurred while connecting to the Board. \n' +
      '\n' +
      "Please check that you've properly flashed the board with the correct firmware.\n" +
      'See: https://github.com/rwaldron/johnny-five/wiki/Getting-Started#trouble-shooting\n' +
      '\n' +
      "If connecting to a Leonardo or Leonardo clone, press the 'Reset' button on the board, wait approximately 11 seconds for complete reset, then run your program again.",
    data: null
  }
}
```

**Comment by moeinrahimi** [comment]
#1536 fixed
