### ISSUE TITLE
Raspberry Pi I2C - Error: , Remote I/O error

### ISSUE THREAD

**Issue by KuhlTime** [rwaldron/johnny-five#1714]
I have just installed `johnny-five` and `rapsi-io` using npm but I am running into the following issue while trying to retrieve my values from my SI7021 sensor. As stated on the `raspi-io` Github repo I installed the package without root privileges. It would be very nice if someone could help me out with this.

I am using Node v10.23.0 on a Raspberry Pi Zero W.

```
pi@raspberrypi:~/j5 $ sudo node main.js
1605110902719 Available Raspi IO
1605110902781 Connected Raspi IO
1605110902854 Repl Initialized
>> events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: , Remote I/O error
Emitted 'error' event at:
    at J5IO.io.on.data (/home/pi/j5/node_modules/johnny-five/lib/board.js:341:39)
    at J5IO.emit (events.js:198:13)
    at J5IO.EventEmitter.emit (domain.js:448:20)
    at readCB (/home/pi/j5/node_modules/j5-io/dist/managers/i2c.js:70:35)
    at /home/pi/j5/node_modules/raspi-i2c/dist/index.js:72:17
```
My code:
```javascript
var five = require("johnny-five");
var Raspi = require("raspi-io").RaspiIO;

var board = new five.Board({
  io: new Raspi()
});

board.on("ready", function() {
  var multi = new five.Multi({
    controller: "SI7021",
  });

  multi.on("change", function() {
    console.log("Thermometer");
    console.log("  celsius           : ", this.thermometer.celsius);
    console.log("  fahrenheit        : ", this.thermometer.fahrenheit);
    console.log("  kelvin            : ", this.thermometer.kelvin);
    console.log("--------------------------------------");

    console.log("Hygrometer");
    console.log("  relative humidity : ", this.hygrometer.relativeHumidity);
    console.log("--------------------------------------");
  });
});
```

A look at i2cdetect reveals that the sensor should be connected.
```
pi@raspberrypi:~/j5 $ sudo i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: 40 -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
```

**Comment by KuhlTime** [comment]
Seems to be a broken sensor and had nothing to do with johnny-five
