### ISSUE TITLE
Version 2.0 problem with Node-Red

### ISSUE THREAD

**Issue by JK40105** [rwaldron/johnny-five#1724]
I use Node-red version 1.2.6 with johnny-five 1.5.0 and the normal settings.js entry "jfive:require("johnny-five"),
        j5board:require("johnny-five").Board({port:"COM5", repl:false})"

After upgrading to johnny-five version 2.0.0 I get the following error at starting Node-Red:
Error loading settings file: C:\Users\Public\Documents\HA1\.node-red\settings.js
TypeError: Class constructor Board cannot be invoked without 'new'
    at Object.<anonymous> (C:\Users\Public\Documents\HA1\.node-red\settings.js:210:40)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\ProgramData\npmglobal\node_modules\node-red\red.js:136:20)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)

How to correct?

**Comment by dtex** [comment]
I don't know node-red, but the error message is pretty straightforward. Since J5 has been modernized with proper ES classes

`j5board:require("johnny-five").Board({port:"COM5", repl:false})`

causes this error

`TypeError: Class constructor Board cannot be invoked without 'new'`

So is it possible to instantiate the board from your program instead of the settings file? Alternately is it possible to use `New` in the settings file?
