### ISSUE TITLE
could not locate the bindings file running blinky.js

### ISSUE THREAD

**Issue by danieluhl** [rwaldron/johnny-five#173]
Running node v0.10.13 on mac osx 10.8.4 I get this error:

Error: Could not locate the bindings file. Tried:
 → .../Node Projects/node_modules/johnny-five/node_modules/serialport/build/serialport.node
 → .../Node Projects/node_modules/johnny-five/node_modules/serialport/build/Debug/serialport.node
 → .../Node Projects/node_modules/johnny-five/node_modules/serialport/build/Release/serialport.node
 → .../Node Projects/node_modules/johnny-five/node_modules/serialport/out/Debug/serialport.node
 → .../Node Projects/node_modules/johnny-five/node_modules/serialport/Debug/serialport.node
 → .../Node Projects/node_modules/johnny-five/node_modules/serialport/out/Release/serialport.node
 → .../Node Projects/node_modules/johnny-five/node_modules/serialport/Release/serialport.node
 → .../Node Projects/node_modules/johnny-five/node_modules/serialport/build/default/serialport.node
 → .../Node Projects/node_modules/johnny-five/node_modules/serialport/compiled/0.10.13/darwin/x64/serialport.node
    at bindings (.../Node Projects/node_modules/johnny-five/node_modules/serialport/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (.../Node Projects/node_modules/johnny-five/node_modules/serialport/serialport.js:7:44)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (.../Documents/Node Projects/node_modules/johnny-five/node_modules/firmata/lib/firmata.js:9:18)
    at Module._compile (module.js:456:26)

**Comment by armstrong99** [comment]
same error but npm rebuild didnt work for me
