### ISSUE TITLE
johnny-five not working

### ISSUE THREAD

**Issue by Sarthak-Arya** [rwaldron/johnny-five#1807]
```
const { Board, Led } = require("johnny-five");
const board = new Board({port:"COM3"});

board.on("ready", () => {

  // Create a standard `led` component instance
  const led = new Led(13);
  this.repl.inject({
    led: led
  });
  // "blink" the led in 500ms
  // on-off phase periods
  led.blink(1000);
});
```
Above is my code

<img width="359" alt="Screenshot 2022-12-29 235929" src="https://user-images.githubusercontent.com/70600000/209994441-f8937701-4e0f-4f03-bc71-c166e5ac56e2.png">

Here is the output is not showing anything 
I am using Windows 11 x64 bit system

**Comment by Jahson17** [comment]
Is it throwing an error like "cannot find module 'firmata' " ???

Or what's the result actually..

**Comment by abdooo9** [comment]
> Is it throwing an error like "cannot find module 'firmata' " ???

I don't think so, but I'm facing this error, is there a solution?, I tried install firmata package but always fails: `npm ERR`

**Comment by princeborn1999** [comment]
I'm facing same problem.

**Comment by WyattSanders** [comment]
> Is it throwing an error like "cannot find module 'firmata' " ???
> 
> Or what's the result actually..

Error: Cannot find module 'firmata'

It's almost a year later and I'm having the same issue with no ability to find a solution.

**Comment by tbaltrushaitis** [comment]
`npm i firmata`

**Comment by tbaltrushaitis** [comment]
> ```
> const { Board, Led } = require("johnny-five");
> const board = new Board({port:"COM3"});
> 
> board.on("ready", () => {
> 
>   // Create a standard `led` component instance
>   const led = new Led(13);
>   this.repl.inject({
>     led: led
>   });
>   // "blink" the led in 500ms
>   // on-off phase periods
>   led.blink(1000);
> });
> ```
> 
> Above is my code
> 
> <img alt="Screenshot 2022-12-29 235929" width="359" src="https://user-images.githubusercontent.com/70600000/209994441-f8937701-4e0f-4f03-bc71-c166e5ac56e2.png">
> 
> Here is the output is not showing anything I am using Windows 11 x64 bit system

Your code shouldn't output anything. It should blink the default led on your board (of course if it is really on port 'COM3')

**Comment by tbaltrushaitis** [comment]
Also I'm not sure if `this` would represent your board because of `() => {}`

**Comment by WyattSanders** [comment]
> `npm i firmata`

This wouldn't fix it, and there would be a laundry list of problems that would follow. 
**I have however figured out the root cause for this issue and others**
People trying to run Johnny-five with a fresh install of Windows 10 or 11 and windows build tools 2022 CANNOT install johnny-five with "npm install" I have found that you need node version 13.14.0 or 14.17.0 (if you tried installing johnny-five with a newer version you need to delete your node_modules folder then change versions of node with nvm-windows) then install VS Build Tools 2019 (VS Build Tools 2022 will not work!) with C++ development. 

After this johnny-five can install successfully with npm install. (Antivirus may also need turned off, run from powershell with administrator privileges too)

VS Build Tools 2019 Download: https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16&src=myvs&utm_medium=microsoft&utm_source=my.visualstudio.com&utm_campaign=download&utm_content=vs+buildtools+2019

![image](https://github.com/rwaldron/johnny-five/assets/7440888/c7e0c98d-3c5c-4cbd-b274-8418ee083c7c)

**Comment by reymesson1** [comment]
Remember also to turn off any Bluetooth connection, make sure that the package.json has into script: "firmata": "firmata-party uno --debug" and npm run firmata. And then node index.js

**Comment by S9963hd** [comment]
i tried so many ways to rectify this issue,but i can't
 
PS D:\J5> node index.js
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'serialport'
Require stack:
- D:\J5\node_modules\johnny-five\lib\board.js
- D:\J5\node_modules\johnny-five\lib\accelerometer.js
- D:\J5\node_modules\johnny-five\lib\johnny-five.js
- D:\J5\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Board.detect (D:\J5\node_modules\johnny-five\lib\board.js:35:20)
    at new Board (D:\J5\node_modules\johnny-five\lib\board.js:291:23)
    at Object.<anonymous> (D:\J5\index.js:2:15)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\J5\\node_modules\\johnny-five\\lib\\board.js',
    'D:\\J5\\node_modules\\johnny-five\\lib\\accelerometer.js',
    'D:\\J5\\node_modules\\johnny-five\\lib\\johnny-five.js',
    'D:\\J5\\index.js'
  ]
}

Node.js v18.18.0
PS D:\J5>

**Comment by tbaltrushaitis** [comment]
> i tried so many ways to rectify this issue,but i can't
> 
> PS D:\J5> node index.js node:internal/modules/cjs/loader:1080 throw err; ^
> 
> Error: Cannot find module 'serialport' 

Install it as described [here](https://serialport.io/docs/guide-installation)
