### ISSUE TITLE
gnarly exception when setting type of digital pin to "analog"

### ISSUE THREAD

**Issue by boneskull** [rwaldron/johnny-five#550]
If you do this:

```js
var rgb = new Led.RGB(9, 10, 11);
var red = new Pin({addr: 9, type: 'analog'});
```

It causes the following exception:

```
    this.pins[this.analogPins[pin]].report = value;
                                           ^
>> TypeError: Cannot set property 'report' of undefined
    at Board.reportAnalogPin (/Volumes/samara/projects/boneskull/sparkfun/node_modules/johnny-five/node_modules/firmata/lib/firmata.js:1214:44)
    at Board.analogRead (/Volumes/samara/projects/boneskull/sparkfun/node_modules/johnny-five/node_modules/firmata/lib/firmata.js:567:8)
    at new Pin (/Volumes/samara/projects/boneskull/sparkfun/node_modules/johnny-five/lib/pin.js:122:25)
```

As of this writing I'm unsure if the first line of the reproduction code is necessary.

This looks like "user error", but it should probably be more friendly.

**Comment by divanvisagie** [comment]
Is this still an issue?

**Comment by rwaldron** [comment]
I think so, I will confirm for you today

**Comment by rwaldron** [comment]
Confirmed. I'm working on this, but there are an overwhelming number of cases to handle and I need to take a break or I may lose my mind.

**Comment by rwaldron** [comment]
Forgot to close this when I landed the pin tracking code
